# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :distribute do
    appId = "1:815161465931:android:cc4f4b2f98a292f25b81ce"

    Dir.chdir '../..' do
          sh('flutter', 'packages', 'get')
          sh('flutter', 'clean')
          sh('flutter', 'build', 'apk')
        end
    firebase_app_distribution(
        app: appId,
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
end


  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
